---
# Using 'blockinfile', ansible will replace the same block of text if the 'block' text changes. 
# So this works well with a single host the '-H' option of the 'ssh-keyscan' command (Hash changes on each run)
# See prepApt.yml for handling multiple targets: use `marker`

- hosts: newhosts
  gather_facts: no

  tasks:
  - name: get ssh hashed key
    blockinfile:
      path: ~/.ssh/known_hosts
      create: yes
      block: "{{ lookup('pipe', 'ssh-keyscan -H ' + inventory_hostname) }}"
    delegate_to: 127.0.0.1
